Move my changes to the main repo
aldeed/meteor-schema-index pull request #33
Opened 2024-01-05 11:30 UTC by harryadel

2024-01-05 11:38 UTC, harryadel commented
cc @jankapunkt @StorytellerCZ

2024-01-09 17:18 UTC, StorytellerCZ requested changes

2024-01-09 17:18 UTC, StorytellerCZ commented on package/indexing/package.js
> +  version: '4.0.0',
This should be beta as well.

2024-01-09 17:23 UTC, closed without merging

2024-01-09 17:25 UTC, StorytellerCZ commented
Sorry @harryadel seems to have closed due to changing the main branch. I'm going to clean things up a bit, but you should be fine with re-opening this PR, let's make it the release v4 branch.